### ISSUE TITLE
No online demo?

### ISSUE THREAD

**Issue by arthurwolf** [MichaelMartinez/GPUvsAPI#1]
if this is purely a client-side thing, it'd be neat if you used github pages and let us actually use it without having to set it up.

cheers.

**Comment by MichaelMartinez** [comment]
Great idea! It is now setup: [here](https://michaelmartinez.github.io/GPUvsAPI/)

**Comment by MichaelMartinez** [comment]
Great idea! It is now setup: [here](https://michaelmartinez.github.io/GPUvsAPI/)

**Comment by arthurwolf** [comment]
amazing, thanks
